DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS user_items CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    user_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar,
    name     varchar
);

CREATE TABLE IF NOT EXISTS item
(
    item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar,
    available bit
);

CREATE TABLE IF NOT EXISTS user_items
(
    user_id integer,
    item_id integer
);

ALTER TABLE user_items
    ADD FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE user_items
    ADD FOREIGN KEY (item_id) REFERENCES item (item_id) ON DELETE CASCADE;

